// GERADO por tools/classes/gen_tier2.py a partir de tools/classes/specs.py. Não edite à mão.
import type { CounterId } from './profile';
import type { ProficiencyId } from './proficiencies';

/** 90 especializações (Tier 2): 15 classes × 6 (3 puras + 3 híbridas). P = pura · C = pura com contador de menor nível · H = híbrida · E = N elementos livres (Mago). */
export interface SpecRow { id: string; name: string; parent: string; kind: 'P' | 'C' | 'H' | 'E'; skills: Partial<Record<ProficiencyId, number>>; counter?: CounterId; elements?: { count: number; level: number }; tagline: string; }
export const TIER2_SPECS: SpecRow[] = [
  { id: 'evocador', name: 'Evocador', parent: 'mago', kind: 'P', skills: { magic: 38 }, tagline: 'Explosões de magia concentradas em um alvo.' },
  { id: 'destruidor', name: 'Destruidor', parent: 'mago', kind: 'P', skills: { magic: 38 }, counter: 'bossCrits', tagline: 'Arrasa chefes com magias críticas.' },
  { id: 'ritualista', name: 'Ritualista', parent: 'mago', kind: 'C', skills: { magic: 35 }, counter: 'buffsApplied', tagline: 'Rituais que potencializam a equipe inteira.' },
  { id: 'elementalista', name: 'Elementalista', parent: 'mago', kind: 'E', skills: {  }, elements: { count: 2, level: 35 }, tagline: 'Domina dois ou mais elementos ao mesmo tempo.' },
  { id: 'prismatico', name: 'Prismático', parent: 'mago', kind: 'E', skills: {  }, elements: { count: 3, level: 30 }, tagline: 'Combina muitos elementos para quebrar qualquer resistência.' },
  { id: 'polimata', name: 'Polímata', parent: 'mago', kind: 'E', skills: {  }, elements: { count: 5, level: 25 }, tagline: 'Conhece quase todos os elementos.' },
  { id: 'gladiador', name: 'Gladiador', parent: 'guerreiro', kind: 'P', skills: { melee: 38 }, counter: 'crits', tagline: 'Luta para a plateia: críticos e golpes em área.' },
  { id: 'berserker', name: 'Berserker', parent: 'guerreiro', kind: 'P', skills: { melee: 38 }, counter: 'damageTaken', tagline: 'Quanto mais apanha, mais bate.' },
  { id: 'campeao', name: 'Campeão', parent: 'guerreiro', kind: 'P', skills: { melee: 38 }, counter: 'bossKills', tagline: 'Cresce com cada chefe derrotado.' },
  { id: 'legionario', name: 'Legionário', parent: 'guerreiro', kind: 'H', skills: { melee: 35, defense: 35 }, tagline: 'Soldado disciplinado: ataque e escudo.' },
  { id: 'lutador_de_arena', name: 'Lutador de Arena', parent: 'guerreiro', kind: 'H', skills: { melee: 35, physical: 35 }, tagline: 'Punhos e aço: combos físicos rápidos.' },
  { id: 'brigao', name: 'Brigão', parent: 'guerreiro', kind: 'H', skills: { defense: 35, physical: 35 }, tagline: 'Valentão resistente: socos e escudo.' },
  { id: 'paladino', name: 'Paladino', parent: 'guardiao', kind: 'H', skills: { defense: 35, holy: 35 }, tagline: 'Escudo e luz: protege e cura os aliados.' },
  { id: 'cavaleiro_negro', name: 'Cavaleiro Negro', parent: 'guardiao', kind: 'H', skills: { defense: 35, death: 35 }, tagline: 'Armadura sombria que drena a vida do inimigo.' },
  { id: 'bastiao', name: 'Bastião', parent: 'guardiao', kind: 'P', skills: { defense: 38 }, counter: 'damageTaken', tagline: 'Quanto mais dano absorve, mais forte fica.' },
  { id: 'sentinela', name: 'Sentinela', parent: 'guardiao', kind: 'P', skills: { defense: 38 }, tagline: 'Vigia constante: resistência acima de tudo.' },
  { id: 'colosso', name: 'Colosso', parent: 'guardiao', kind: 'P', skills: { defense: 38 }, counter: 'bossKills', tagline: 'Um gigante de ferro que derruba chefes.' },
  { id: 'escudeiro_de_ferro', name: 'Escudeiro de Ferro', parent: 'guardiao', kind: 'H', skills: { defense: 35, melee: 35 }, tagline: 'Usa o escudo como arma.' },
  { id: 'assassino', name: 'Assassino', parent: 'ladino', kind: 'P', skills: { melee: 38 }, counter: 'bossCrits', tagline: 'Golpes críticos devastadores em chefes.' },
  { id: 'mestre_das_sombras', name: 'Mestre das Sombras', parent: 'ladino', kind: 'H', skills: { melee: 35, death: 35 }, tagline: 'Ataca das sombras com lâminas sinistras.' },
  { id: 'duelista', name: 'Duelista', parent: 'ladino', kind: 'P', skills: { melee: 38 }, counter: 'crits', tagline: 'Dança com a lâmina: velocidade e críticos.' },
  { id: 'saqueador', name: 'Saqueador', parent: 'ladino', kind: 'P', skills: { melee: 38 }, counter: 'goldEarned', tagline: 'Rápido nas mãos e no bolso: ouro e drops.' },
  { id: 'envenenador', name: 'Envenenador', parent: 'ladino', kind: 'H', skills: { melee: 35, poison: 35 }, tagline: 'Lâminas banhadas em veneno.' },
  { id: 'bailarino_de_laminas', name: 'Bailarino de Lâminas', parent: 'ladino', kind: 'H', skills: { melee: 35, physical: 35 }, tagline: 'Giros cortantes que atingem todos.' },
  { id: 'atirador_de_elite', name: 'Atirador de Elite', parent: 'cacador', kind: 'P', skills: { ranged: 38 }, tagline: 'Cada tiro é uma sentença.' },
  { id: 'mestre_das_feras', name: 'Mestre das Feras', parent: 'cacador', kind: 'H', skills: { ranged: 35, earth: 35 }, tagline: 'Luta ao lado de animais selvagens.' },
  { id: 'franco_atirador', name: 'Franco-Atirador', parent: 'cacador', kind: 'P', skills: { ranged: 38 }, counter: 'bossCrits', tagline: 'Tiros na cabeça de chefes.' },
  { id: 'cacador_de_trofeus', name: 'Caçador de Troféus', parent: 'cacador', kind: 'P', skills: { ranged: 38 }, counter: 'bossKills', tagline: 'Cresce a cada chefe caçado.' },
  { id: 'arqueiro_marcial', name: 'Arqueiro Marcial', parent: 'cacador', kind: 'H', skills: { ranged: 35, physical: 35 }, tagline: 'Flechas cinéticas e rápidas.' },
  { id: 'rastreador', name: 'Rastreador', parent: 'cacador', kind: 'H', skills: { earth: 35, physical: 35 }, tagline: 'Sobrevive na natureza: armadilhas e emboscadas.' },
  { id: 'sumo_sacerdote', name: 'Sumo Sacerdote', parent: 'clerigo', kind: 'C', skills: { holy: 35 }, counter: 'healingDone', tagline: 'A cura em pessoa: salva quem estiver caindo.' },
  { id: 'inquisidor', name: 'Inquisidor', parent: 'clerigo', kind: 'H', skills: { holy: 35, magic: 35 }, tagline: 'Fé como arma: queima os hereges.' },
  { id: 'santo_padroeiro', name: 'Santo Padroeiro', parent: 'clerigo', kind: 'P', skills: { holy: 38 }, counter: 'buffsApplied', tagline: 'Abençoa o grupo com auras duradouras.' },
  { id: 'oraculo', name: 'Oráculo', parent: 'clerigo', kind: 'P', skills: { holy: 38 }, tagline: 'Visões divinas que revelam e castigam.' },
  { id: 'templario', name: 'Templário', parent: 'clerigo', kind: 'H', skills: { holy: 35, defense: 35 }, tagline: 'Escudo da fé: cura e protege na linha de frente.' },
  { id: 'sentinela_arcana', name: 'Sentinela Arcana', parent: 'clerigo', kind: 'H', skills: { magic: 35, defense: 35 }, tagline: 'Magia sagrada em forma de muralha.' },
  { id: 'maestro', name: 'Maestro', parent: 'bardo', kind: 'C', skills: { magic: 35 }, counter: 'buffsApplied', tagline: 'Rege a equipe com buffs sem fim.' },
  { id: 'menestrel_do_caos', name: 'Menestrel do Caos', parent: 'bardo', kind: 'H', skills: { magic: 35, psychic: 35 }, tagline: 'Melodias que enlouquecem os inimigos.' },
  { id: 'trovador', name: 'Trovador', parent: 'bardo', kind: 'P', skills: { magic: 38 }, tagline: 'Baladas épicas que inspiram a equipe.' },
  { id: 'mestre_de_cerimonias', name: 'Mestre de Cerimônias', parent: 'bardo', kind: 'P', skills: { magic: 38 }, counter: 'controlSpells', tagline: 'Domina o palco e prende a atenção dos inimigos.' },
  { id: 'harmonista_sagrado', name: 'Harmonista Sagrado', parent: 'bardo', kind: 'H', skills: { magic: 35, holy: 35 }, tagline: 'Hinos que curam e protegem.' },
  { id: 'cantor_visionario', name: 'Cantor Visionário', parent: 'bardo', kind: 'H', skills: { psychic: 35, holy: 35 }, tagline: 'Canções que revelam e curam a mente.' },
  { id: 'mestre_do_chi', name: 'Mestre do Chi', parent: 'monge', kind: 'H', skills: { physical: 35, magic: 35 }, tagline: 'Energia interior em cada golpe.' },
  { id: 'punho_de_ferro', name: 'Punho de Ferro', parent: 'monge', kind: 'H', skills: { physical: 35, defense: 35 }, tagline: 'Corpo de aço e golpes pesados.' },
  { id: 'punho_veloz', name: 'Punho Veloz', parent: 'monge', kind: 'P', skills: { physical: 38 }, counter: 'crits', tagline: 'Mil socos por segundo.' },
  { id: 'monge_errante', name: 'Monge Errante', parent: 'monge', kind: 'P', skills: { physical: 38 }, tagline: 'Equilibrado: vida, velocidade e resistência.' },
  { id: 'pele_de_pedra', name: 'Pele de Pedra', parent: 'monge', kind: 'P', skills: { physical: 38 }, counter: 'damageTaken', tagline: 'Transforma dano sofrido em força.' },
  { id: 'monge_guerreiro', name: 'Monge Guerreiro', parent: 'monge', kind: 'H', skills: { physical: 35, melee: 35 }, tagline: 'Artes marciais armadas.' },
  { id: 'necromante', name: 'Necromante', parent: 'bruxo', kind: 'P', skills: { death: 38 }, tagline: 'Comanda o poder da morte.' },
  { id: 'epidemiologista', name: 'Epidemiologista', parent: 'bruxo', kind: 'C', skills: { poison: 35 }, counter: 'dotDamage', tagline: 'Doenças que corroem o grupo inimigo.' },
  { id: 'ceifador', name: 'Ceifador', parent: 'bruxo', kind: 'P', skills: { death: 38 }, counter: 'bossKills', tagline: 'Colhe a alma de chefes.' },
  { id: 'arquimago_sombrio', name: 'Arquimago Sombrio', parent: 'bruxo', kind: 'H', skills: { death: 35, magic: 35 }, tagline: 'Magia pura sombria: dano arcano e morte.' },
  { id: 'toxicomante', name: 'Toxicomante', parent: 'bruxo', kind: 'H', skills: { poison: 35, magic: 35 }, tagline: 'Venenos arcanos de ação prolongada.' },
  { id: 'peconhento', name: 'Peçonhento', parent: 'bruxo', kind: 'H', skills: { death: 35, poison: 35 }, tagline: 'Maldições que apodrecem de dentro.' },
  { id: 'mestre_bombardeiro', name: 'Mestre Bombardeiro', parent: 'alquimista', kind: 'H', skills: { ranged: 35, fire: 35 }, tagline: 'Explosivos que limpam a sala.' },
  { id: 'transmutador', name: 'Transmutador', parent: 'alquimista', kind: 'C', skills: { poison: 35 }, counter: 'supportPotionsUsed', tagline: 'Transforma poções em vantagem.' },
  { id: 'herbalista', name: 'Herbalista', parent: 'alquimista', kind: 'P', skills: { poison: 38 }, counter: 'healingDone', tagline: 'Ervas que curam a equipe.' },
  { id: 'quimico_louco', name: 'Químico Louco', parent: 'alquimista', kind: 'P', skills: { poison: 38 }, counter: 'dotDamage', tagline: 'Misturas instáveis de dano contínuo.' },
  { id: 'boticario_atirador', name: 'Boticário Atirador', parent: 'alquimista', kind: 'H', skills: { poison: 35, ranged: 35 }, tagline: 'Arremessa frascos de longe.' },
  { id: 'fogo_liquido', name: 'Fogo Líquido', parent: 'alquimista', kind: 'H', skills: { poison: 35, fire: 35 }, tagline: 'Combustíveis que queimam sem parar.' },
  { id: 'cacador_de_recompensas', name: 'Caçador de Recompensas', parent: 'mercenario', kind: 'C', skills: { melee: 35 }, counter: 'bossKills', tagline: 'Vive de chefes: cada cabeça paga.' },
  { id: 'corsario', name: 'Corsário', parent: 'mercenario', kind: 'C', skills: { melee: 35 }, counter: 'goldEarned', tagline: 'Pilhagem e velocidade: o ouro é a meta.' },
  { id: 'executor', name: 'Executor', parent: 'mercenario', kind: 'P', skills: { melee: 38 }, counter: 'crits', tagline: 'Golpes finais certeiros.' },
  { id: 'guarda_costas', name: 'Guarda-Costas', parent: 'mercenario', kind: 'H', skills: { defense: 35, physical: 35 }, tagline: 'Contratado para proteger: soco e escudo.' },
  { id: 'veterano', name: 'Veterano', parent: 'mercenario', kind: 'H', skills: { melee: 35, defense: 35 }, tagline: 'Anos de guerra: casca grossa.' },
  { id: 'brutamontes', name: 'Brutamontes', parent: 'mercenario', kind: 'H', skills: { melee: 35, physical: 35 }, tagline: 'Força bruta que esmaga tudo.' },
  { id: 'forjador_de_laminas', name: 'Forjador de Lâminas', parent: 'mestre_runico', kind: 'H', skills: { magic: 35, melee: 35 }, tagline: 'Lâminas gravadas com runas de poder.' },
  { id: 'guardiao_das_runas', name: 'Guardião das Runas', parent: 'mestre_runico', kind: 'H', skills: { magic: 35, defense: 35 }, tagline: 'Runas que protegem o grupo.' },
  { id: 'escrivao_de_runas', name: 'Escrivão de Runas', parent: 'mestre_runico', kind: 'P', skills: { magic: 38 }, tagline: 'Glifos explosivos de grande alcance.' },
  { id: 'runa_ancestral', name: 'Runa Ancestral', parent: 'mestre_runico', kind: 'P', skills: { magic: 38 }, counter: 'buffsApplied', tagline: 'Poder antigo que reforça aliados.' },
  { id: 'selador', name: 'Selador', parent: 'mestre_runico', kind: 'P', skills: { magic: 38 }, counter: 'controlSpells', tagline: 'Sela os inimigos no lugar.' },
  { id: 'runa_flamejante', name: 'Runa Flamejante', parent: 'mestre_runico', kind: 'H', skills: { magic: 35, fire: 35 }, tagline: 'Runas de fogo que queimam em área.' },
  { id: 'mestre_dos_espelhos', name: 'Mestre dos Espelhos', parent: 'ilusionista', kind: 'H', skills: { psychic: 35, magic: 35 }, tagline: 'Imagens que desviam o dano.' },
  { id: 'hipnotizador', name: 'Hipnotizador', parent: 'ilusionista', kind: 'C', skills: { psychic: 35 }, counter: 'controlSpells', tagline: 'Olhar que paralisa os inimigos.' },
  { id: 'pesadelo', name: 'Pesadelo', parent: 'ilusionista', kind: 'P', skills: { psychic: 38 }, tagline: 'Terror mental de alto dano.' },
  { id: 'tecelao_de_sonhos', name: 'Tecelão de Sonhos', parent: 'ilusionista', kind: 'P', skills: { psychic: 38 }, counter: 'buffsApplied', tagline: 'Véus de sonho que protegem o grupo.' },
  { id: 'miragem_eletrica', name: 'Miragem Elétrica', parent: 'ilusionista', kind: 'H', skills: { psychic: 35, energy: 35 }, tagline: 'Ilusões que dão choque.' },
  { id: 'arcanista_ilusorio', name: 'Arcanista Ilusório', parent: 'ilusionista', kind: 'H', skills: { magic: 35, energy: 35 }, tagline: 'Ilusões de energia pura.' },
  { id: 'forma_feral', name: 'Forma Feral', parent: 'druida', kind: 'H', skills: { earth: 35, melee: 35 }, tagline: 'Transforma-se em fera de garras.' },
  { id: 'guardiao_da_natureza', name: 'Guardião da Natureza', parent: 'druida', kind: 'H', skills: { earth: 35, magic: 35 }, tagline: 'A floresta protege o grupo.' },
  { id: 'curandeiro_verde', name: 'Curandeiro Verde', parent: 'druida', kind: 'P', skills: { earth: 38 }, counter: 'healingDone', tagline: 'Seiva que cura sem parar.' },
  { id: 'senhor_das_bestas', name: 'Senhor das Bestas', parent: 'druida', kind: 'P', skills: { earth: 38 }, tagline: 'Invoca matilhas selvagens.' },
  { id: 'espinheiro', name: 'Espinheiro', parent: 'druida', kind: 'P', skills: { earth: 38 }, counter: 'dotDamage', tagline: 'Espinhos e veneno: dano contínuo da terra.' },
  { id: 'peconha_verde', name: 'Peçonha Verde', parent: 'druida', kind: 'H', skills: { earth: 35, poison: 35 }, tagline: 'Esporos e toxinas da natureza.' },
  { id: 'engenheiro_de_torretas', name: 'Engenheiro de Torretas', parent: 'artilheiro', kind: 'H', skills: { ranged: 35, energy: 35 }, tagline: 'Torretas que atiram por você.' },
  { id: 'exotraje', name: 'Exotraje', parent: 'artilheiro', kind: 'H', skills: { ranged: 35, defense: 35 }, tagline: 'Armadura motorizada: atira e aguenta.' },
  { id: 'franco_explosivo', name: 'Franco Explosivo', parent: 'artilheiro', kind: 'P', skills: { ranged: 38 }, counter: 'crits', tagline: 'Munição perfurante e explosiva.' },
  { id: 'demolidor', name: 'Demolidor', parent: 'artilheiro', kind: 'P', skills: { ranged: 38 }, counter: 'bossKills', tagline: 'Cargas que derrubam chefes.' },
  { id: 'metralhador', name: 'Metralhador', parent: 'artilheiro', kind: 'P', skills: { ranged: 38 }, tagline: 'Cadência máxima: balas sem parar.' },
  { id: 'artilheiro_flamejante', name: 'Artilheiro Flamejante', parent: 'artilheiro', kind: 'H', skills: { ranged: 35, fire: 35 }, tagline: 'Balas incendiárias.' },
];

export interface SpecPassive { name: string; description: string; effects: { effect: string; value: number }[]; }
export const SPEC_PASSIVES: Record<string, SpecPassive> = {
  evocador: { name: 'Poder Concentrado', description: '+14% de poder mágico e +4% de chance de crítico.', effects: [{ effect: 'magicPower', value: 0.14 }, { effect: 'crit', value: 0.04 }] },
  destruidor: { name: 'Fúria Arcana', description: '+10% de poder mágico e +6% de chance de crítico.', effects: [{ effect: 'magicPower', value: 0.1 }, { effect: 'crit', value: 0.06 }] },
  ritualista: { name: 'Círculo Ritual', description: '+15% de mana máxima e 6% de recarga mais rápida.', effects: [{ effect: 'maxMana', value: 0.15 }, { effect: 'cooldown', value: 0.06 }] },
  elementalista: { name: 'Harmonia Elemental', description: '+10% de poder mágico, +10% de mana máxima, +10% de dano das magias do elemento em foco, +15% de chance de queimar em magias de fogo e +10% do dano de gelo vira barreira.', effects: [{ effect: 'magicPower', value: 0.1 }, { effect: 'maxMana', value: 0.1 }, { effect: 'focusMagicDamage', value: 0.1 }, { effect: 'burnOnFireHit', value: 0.15 }, { effect: 'iceBarrier', value: 0.1 }] },
  prismatico: { name: 'Espectro Prismático', description: '+12% de poder mágico, 8% de recarga mais rápida e +8% de crítico em magias de fogo e energia.', effects: [{ effect: 'magicPower', value: 0.12 }, { effect: 'cooldown', value: 0.08 }, { effect: 'plasmaCrit', value: 0.08 }] },
  polimata: { name: 'Saber Universal', description: '+10% de poder mágico, +12% de mana máxima e 5% de recarga mais rápida.', effects: [{ effect: 'magicPower', value: 0.1 }, { effect: 'maxMana', value: 0.12 }, { effect: 'cooldown', value: 0.05 }] },
  gladiador: { name: 'Aclamado da Arena', description: '+10% de ataque e +8% de velocidade de ataque.', effects: [{ effect: 'attack', value: 0.1 }, { effect: 'attackSpeed', value: 0.08 }] },
  berserker: { name: 'Fúria Sanguinária', description: '+14% de ataque e +6% de vida.', effects: [{ effect: 'attack', value: 0.14 }, { effect: 'maxHp', value: 0.06 }] },
  campeao: { name: 'Glória do Campeão', description: '+10% de ataque, +5% de chance de crítico e +6% de defesa.', effects: [{ effect: 'attack', value: 0.1 }, { effect: 'crit', value: 0.05 }, { effect: 'defense', value: 0.06 }] },
  legionario: { name: 'Disciplina de Legião', description: '+12% de defesa, +8% de ataque e +6% de vida.', effects: [{ effect: 'defense', value: 0.12 }, { effect: 'attack', value: 0.08 }, { effect: 'maxHp', value: 0.06 }] },
  lutador_de_arena: { name: 'Punhos de Aço', description: '+12% de ataque e +8% de velocidade de ataque.', effects: [{ effect: 'attack', value: 0.12 }, { effect: 'attackSpeed', value: 0.08 }] },
  brigao: { name: 'Casca de Valentão', description: '+10% de defesa, +8% de ataque e +6% de vida.', effects: [{ effect: 'defense', value: 0.1 }, { effect: 'attack', value: 0.08 }, { effect: 'maxHp', value: 0.06 }] },
  paladino: { name: 'Juramento Sagrado', description: '+12% de defesa, +8% de resistência e +6% de poder mágico.', effects: [{ effect: 'defense', value: 0.12 }, { effect: 'resistance', value: 0.08 }, { effect: 'magicPower', value: 0.06 }] },
  cavaleiro_negro: { name: 'Pacto Sombrio', description: '+10% de ataque, +10% de defesa e +6% de vida.', effects: [{ effect: 'attack', value: 0.1 }, { effect: 'defense', value: 0.1 }, { effect: 'maxHp', value: 0.06 }] },
  bastiao: { name: 'Muralha Inabalável', description: '+16% de defesa e +10% de vida.', effects: [{ effect: 'defense', value: 0.16 }, { effect: 'maxHp', value: 0.1 }] },
  sentinela: { name: 'Vigília Constante', description: '+12% de resistência e +10% de defesa.', effects: [{ effect: 'resistance', value: 0.12 }, { effect: 'defense', value: 0.1 }] },
  colosso: { name: 'Gigante de Ferro', description: '+18% de vida e +8% de defesa.', effects: [{ effect: 'maxHp', value: 0.18 }, { effect: 'defense', value: 0.08 }] },
  escudeiro_de_ferro: { name: 'Escudo Ofensivo', description: '+10% de defesa e +10% de ataque.', effects: [{ effect: 'defense', value: 0.1 }, { effect: 'attack', value: 0.1 }] },
  assassino: { name: 'Golpe de Misericórdia', description: '+10% de chance de crítico e +8% de ataque.', effects: [{ effect: 'crit', value: 0.1 }, { effect: 'attack', value: 0.08 }] },
  mestre_das_sombras: { name: 'Véu das Sombras', description: '+10% de velocidade de ataque e +6% de chance de crítico.', effects: [{ effect: 'attackSpeed', value: 0.1 }, { effect: 'crit', value: 0.06 }] },
  duelista: { name: 'Dança da Lâmina', description: '+12% de velocidade de ataque e +6% de chance de crítico.', effects: [{ effect: 'attackSpeed', value: 0.12 }, { effect: 'crit', value: 0.06 }] },
  saqueador: { name: 'Mãos Leves', description: '+8% de ataque e +8% de velocidade de ataque.', effects: [{ effect: 'attack', value: 0.08 }, { effect: 'attackSpeed', value: 0.08 }] },
  envenenador: { name: 'Lâmina Peçonhenta', description: '+8% de ataque e +6% de chance de crítico.', effects: [{ effect: 'attack', value: 0.08 }, { effect: 'crit', value: 0.06 }] },
  bailarino_de_laminas: { name: 'Passos Cortantes', description: '+12% de velocidade de ataque e +5% de defesa.', effects: [{ effect: 'attackSpeed', value: 0.12 }, { effect: 'defense', value: 0.05 }] },
  atirador_de_elite: { name: 'Mira Perfeita', description: '+10% de chance de crítico e +8% de ataque.', effects: [{ effect: 'crit', value: 0.1 }, { effect: 'attack', value: 0.08 }] },
  mestre_das_feras: { name: 'Laço Selvagem', description: '+10% de vida e +8% de ataque.', effects: [{ effect: 'maxHp', value: 0.1 }, { effect: 'attack', value: 0.08 }] },
  franco_atirador: { name: 'Tiro na Cabeça', description: '+12% de chance de crítico e +6% de ataque.', effects: [{ effect: 'crit', value: 0.12 }, { effect: 'attack', value: 0.06 }] },
  cacador_de_trofeus: { name: 'Troféu de Caça', description: '+10% de ataque e +6% de vida.', effects: [{ effect: 'attack', value: 0.1 }, { effect: 'maxHp', value: 0.06 }] },
  arqueiro_marcial: { name: 'Flecha Cinética', description: '+10% de ataque e +8% de velocidade de ataque.', effects: [{ effect: 'attack', value: 0.1 }, { effect: 'attackSpeed', value: 0.08 }] },
  rastreador: { name: 'Instinto de Sobrevivência', description: '+10% de defesa, +10% de vida e +5% de resistência.', effects: [{ effect: 'defense', value: 0.1 }, { effect: 'maxHp', value: 0.1 }, { effect: 'resistance', value: 0.05 }] },
  sumo_sacerdote: { name: 'Mão da Providência', description: '+12% de poder mágico e +8% de mana máxima.', effects: [{ effect: 'magicPower', value: 0.12 }, { effect: 'maxMana', value: 0.08 }] },
  inquisidor: { name: 'Fogo da Fé', description: '+12% de poder mágico e +6% de ataque.', effects: [{ effect: 'magicPower', value: 0.12 }, { effect: 'attack', value: 0.06 }] },
  santo_padroeiro: { name: 'Aura Benevolente', description: '+10% de mana máxima, 6% de recarga mais rápida e +5% de resistência.', effects: [{ effect: 'maxMana', value: 0.1 }, { effect: 'cooldown', value: 0.06 }, { effect: 'resistance', value: 0.05 }] },
  oraculo: { name: 'Visão Divina', description: '+10% de poder mágico, +5% de chance de crítico e 6% de recarga mais rápida.', effects: [{ effect: 'magicPower', value: 0.1 }, { effect: 'crit', value: 0.05 }, { effect: 'cooldown', value: 0.06 }] },
  templario: { name: 'Escudo da Fé', description: '+10% de defesa, +8% de resistência e +6% de vida.', effects: [{ effect: 'defense', value: 0.1 }, { effect: 'resistance', value: 0.08 }, { effect: 'maxHp', value: 0.06 }] },
  sentinela_arcana: { name: 'Muralha de Luz', description: '+10% de defesa, +10% de poder mágico e +6% de mana máxima.', effects: [{ effect: 'defense', value: 0.1 }, { effect: 'magicPower', value: 0.1 }, { effect: 'maxMana', value: 0.06 }] },
  maestro: { name: 'Regente', description: '+10% de poder mágico e 8% de recarga mais rápida.', effects: [{ effect: 'magicPower', value: 0.1 }, { effect: 'cooldown', value: 0.08 }] },
  menestrel_do_caos: { name: 'Melodia Caótica', description: '+12% de poder mágico e +5% de chance de crítico.', effects: [{ effect: 'magicPower', value: 0.12 }, { effect: 'crit', value: 0.05 }] },
  trovador: { name: 'Voz de Ouro', description: '+12% de mana máxima e +8% de poder mágico.', effects: [{ effect: 'maxMana', value: 0.12 }, { effect: 'magicPower', value: 0.08 }] },
  mestre_de_cerimonias: { name: 'Presença de Palco', description: '8% de recarga mais rápida, +6% de resistência e +6% de poder mágico.', effects: [{ effect: 'cooldown', value: 0.08 }, { effect: 'resistance', value: 0.06 }, { effect: 'magicPower', value: 0.06 }] },
  harmonista_sagrado: { name: 'Hino Sagrado', description: '+10% de mana máxima, +8% de poder mágico e +6% de resistência.', effects: [{ effect: 'maxMana', value: 0.1 }, { effect: 'magicPower', value: 0.08 }, { effect: 'resistance', value: 0.06 }] },
  cantor_visionario: { name: 'Canto Profético', description: '+10% de poder mágico, +8% de resistência e +8% de mana máxima.', effects: [{ effect: 'magicPower', value: 0.1 }, { effect: 'resistance', value: 0.08 }, { effect: 'maxMana', value: 0.08 }] },
  mestre_do_chi: { name: 'Fluxo do Chi', description: '+10% de poder mágico e +8% de velocidade de ataque.', effects: [{ effect: 'magicPower', value: 0.1 }, { effect: 'attackSpeed', value: 0.08 }] },
  punho_de_ferro: { name: 'Pele de Ferro', description: '+12% de defesa e +8% de resistência.', effects: [{ effect: 'defense', value: 0.12 }, { effect: 'resistance', value: 0.08 }] },
  punho_veloz: { name: 'Mãos Relâmpago', description: '+14% de velocidade de ataque e +6% de chance de crítico.', effects: [{ effect: 'attackSpeed', value: 0.14 }, { effect: 'crit', value: 0.06 }] },
  monge_errante: { name: 'Caminho do Viajante', description: '+10% de vida, +8% de velocidade de ataque e +4% de resistência.', effects: [{ effect: 'maxHp', value: 0.1 }, { effect: 'attackSpeed', value: 0.08 }, { effect: 'resistance', value: 0.04 }] },
  pele_de_pedra: { name: 'Corpo de Pedra', description: '+14% de vida e +10% de defesa.', effects: [{ effect: 'maxHp', value: 0.14 }, { effect: 'defense', value: 0.1 }] },
  monge_guerreiro: { name: 'Arte Marcial', description: '+12% de ataque e +8% de velocidade de ataque.', effects: [{ effect: 'attack', value: 0.12 }, { effect: 'attackSpeed', value: 0.08 }] },
  necromante: { name: 'Senhor dos Mortos', description: '+14% de poder mágico e +6% de mana máxima.', effects: [{ effect: 'magicPower', value: 0.14 }, { effect: 'maxMana', value: 0.06 }] },
  epidemiologista: { name: 'Contágio', description: '+10% de poder mágico e +5% de chance de crítico.', effects: [{ effect: 'magicPower', value: 0.1 }, { effect: 'crit', value: 0.05 }] },
  ceifador: { name: 'Colheita', description: '+12% de poder mágico e +5% de chance de crítico.', effects: [{ effect: 'magicPower', value: 0.12 }, { effect: 'crit', value: 0.05 }] },
  arquimago_sombrio: { name: 'Arcano Sombrio', description: '+14% de poder mágico e +6% de mana máxima.', effects: [{ effect: 'magicPower', value: 0.14 }, { effect: 'maxMana', value: 0.06 }] },
  toxicomante: { name: 'Veneno Arcano', description: '+10% de poder mágico, +5% de chance de crítico e +6% de mana máxima.', effects: [{ effect: 'magicPower', value: 0.1 }, { effect: 'crit', value: 0.05 }, { effect: 'maxMana', value: 0.06 }] },
  peconhento: { name: 'Maldição Venenosa', description: '+10% de poder mágico e +5% de chance de crítico.', effects: [{ effect: 'magicPower', value: 0.1 }, { effect: 'crit', value: 0.05 }] },
  mestre_bombardeiro: { name: 'Pólvora Alquímica', description: '+10% de ataque e +5% de chance de crítico.', effects: [{ effect: 'attack', value: 0.1 }, { effect: 'crit', value: 0.05 }] },
  transmutador: { name: 'Transmutação', description: '+10% de mana máxima e +8% de poder mágico.', effects: [{ effect: 'maxMana', value: 0.1 }, { effect: 'magicPower', value: 0.08 }] },
  herbalista: { name: 'Ervas Medicinais', description: '+10% de vida e +8% de poder mágico.', effects: [{ effect: 'maxHp', value: 0.1 }, { effect: 'magicPower', value: 0.08 }] },
  quimico_louco: { name: 'Mistura Instável', description: '+10% de ataque e +6% de chance de crítico.', effects: [{ effect: 'attack', value: 0.1 }, { effect: 'crit', value: 0.06 }] },
  boticario_atirador: { name: 'Frascos de Longe', description: '+10% de ataque e +6% de velocidade de ataque.', effects: [{ effect: 'attack', value: 0.1 }, { effect: 'attackSpeed', value: 0.06 }] },
  fogo_liquido: { name: 'Combustível', description: '+10% de poder mágico, +6% de ataque e +4% de chance de crítico.', effects: [{ effect: 'magicPower', value: 0.1 }, { effect: 'attack', value: 0.06 }, { effect: 'crit', value: 0.04 }] },
  cacador_de_recompensas: { name: 'Contrato de Caça', description: '+10% de ataque e +5% de chance de crítico.', effects: [{ effect: 'attack', value: 0.1 }, { effect: 'crit', value: 0.05 }] },
  corsario: { name: 'Butim', description: '+8% de ataque e +8% de velocidade de ataque.', effects: [{ effect: 'attack', value: 0.08 }, { effect: 'attackSpeed', value: 0.08 }] },
  executor: { name: 'Golpe Final', description: '+12% de ataque e +6% de chance de crítico.', effects: [{ effect: 'attack', value: 0.12 }, { effect: 'crit', value: 0.06 }] },
  guarda_costas: { name: 'Contrato de Proteção', description: '+10% de defesa, +10% de vida e +6% de ataque.', effects: [{ effect: 'defense', value: 0.1 }, { effect: 'maxHp', value: 0.1 }, { effect: 'attack', value: 0.06 }] },
  veterano: { name: 'Casca Grossa', description: '+12% de defesa e +10% de vida.', effects: [{ effect: 'defense', value: 0.12 }, { effect: 'maxHp', value: 0.1 }] },
  brutamontes: { name: 'Força Bruta', description: '+14% de ataque e +6% de vida.', effects: [{ effect: 'attack', value: 0.14 }, { effect: 'maxHp', value: 0.06 }] },
  forjador_de_laminas: { name: 'Lâmina Gravada', description: '+10% de ataque e +8% de poder mágico.', effects: [{ effect: 'attack', value: 0.1 }, { effect: 'magicPower', value: 0.08 }] },
  guardiao_das_runas: { name: 'Runa Protetora', description: '+10% de defesa, +8% de poder mágico e +5% de resistência.', effects: [{ effect: 'defense', value: 0.1 }, { effect: 'magicPower', value: 0.08 }, { effect: 'resistance', value: 0.05 }] },
  escrivao_de_runas: { name: 'Caligrafia Arcana', description: '+12% de poder mágico e 6% de recarga mais rápida.', effects: [{ effect: 'magicPower', value: 0.12 }, { effect: 'cooldown', value: 0.06 }] },
  runa_ancestral: { name: 'Poder Ancestral', description: '+10% de mana máxima, +8% de poder mágico e 5% de recarga mais rápida.', effects: [{ effect: 'maxMana', value: 0.1 }, { effect: 'magicPower', value: 0.08 }, { effect: 'cooldown', value: 0.05 }] },
  selador: { name: 'Selo Restritivo', description: '8% de recarga mais rápida, +8% de poder mágico e +5% de resistência.', effects: [{ effect: 'cooldown', value: 0.08 }, { effect: 'magicPower', value: 0.08 }, { effect: 'resistance', value: 0.05 }] },
  runa_flamejante: { name: 'Runas de Fogo', description: '+12% de poder mágico e +6% de ataque.', effects: [{ effect: 'magicPower', value: 0.12 }, { effect: 'attack', value: 0.06 }] },
  mestre_dos_espelhos: { name: 'Reflexos', description: '+10% de poder mágico e +8% de defesa.', effects: [{ effect: 'magicPower', value: 0.1 }, { effect: 'defense', value: 0.08 }] },
  hipnotizador: { name: 'Olhar Hipnótico', description: '8% de recarga mais rápida e +8% de poder mágico.', effects: [{ effect: 'cooldown', value: 0.08 }, { effect: 'magicPower', value: 0.08 }] },
  pesadelo: { name: 'Terror Noturno', description: '+14% de poder mágico e +4% de chance de crítico.', effects: [{ effect: 'magicPower', value: 0.14 }, { effect: 'crit', value: 0.04 }] },
  tecelao_de_sonhos: { name: 'Sonhos Lúcidos', description: '+12% de mana máxima e 6% de recarga mais rápida.', effects: [{ effect: 'maxMana', value: 0.12 }, { effect: 'cooldown', value: 0.06 }] },
  miragem_eletrica: { name: 'Miragem Elétrica', description: '+10% de poder mágico, +6% de velocidade de ataque e +5% de chance de crítico.', effects: [{ effect: 'magicPower', value: 0.1 }, { effect: 'attackSpeed', value: 0.06 }, { effect: 'crit', value: 0.05 }] },
  arcanista_ilusorio: { name: 'Energia Ilusória', description: '+12% de poder mágico e 6% de recarga mais rápida.', effects: [{ effect: 'magicPower', value: 0.12 }, { effect: 'cooldown', value: 0.06 }] },
  forma_feral: { name: 'Instinto Feral', description: '+10% de ataque e +10% de vida.', effects: [{ effect: 'attack', value: 0.1 }, { effect: 'maxHp', value: 0.1 }] },
  guardiao_da_natureza: { name: 'Vínculo Natural', description: '+10% de poder mágico, +8% de resistência e +6% de vida.', effects: [{ effect: 'magicPower', value: 0.1 }, { effect: 'resistance', value: 0.08 }, { effect: 'maxHp', value: 0.06 }] },
  curandeiro_verde: { name: 'Seiva Vital', description: '+10% de poder mágico e +10% de mana máxima.', effects: [{ effect: 'magicPower', value: 0.1 }, { effect: 'maxMana', value: 0.1 }] },
  senhor_das_bestas: { name: 'Chamado Selvagem', description: '+10% de vida, +6% de ataque e +6% de poder mágico.', effects: [{ effect: 'maxHp', value: 0.1 }, { effect: 'attack', value: 0.06 }, { effect: 'magicPower', value: 0.06 }] },
  espinheiro: { name: 'Espinhos Venenosos', description: '+8% de resistência e +10% de poder mágico.', effects: [{ effect: 'resistance', value: 0.08 }, { effect: 'magicPower', value: 0.1 }] },
  peconha_verde: { name: 'Veneno da Terra', description: '+10% de poder mágico e +5% de chance de crítico.', effects: [{ effect: 'magicPower', value: 0.1 }, { effect: 'crit', value: 0.05 }] },
  engenheiro_de_torretas: { name: 'Torreta Auxiliar', description: '+10% de ataque e +8% de velocidade de ataque.', effects: [{ effect: 'attack', value: 0.1 }, { effect: 'attackSpeed', value: 0.08 }] },
  exotraje: { name: 'Armadura Motorizada', description: '+12% de defesa e +10% de vida.', effects: [{ effect: 'defense', value: 0.12 }, { effect: 'maxHp', value: 0.1 }] },
  franco_explosivo: { name: 'Munição Perfurante', description: '+8% de chance de crítico e +10% de ataque.', effects: [{ effect: 'crit', value: 0.08 }, { effect: 'attack', value: 0.1 }] },
  demolidor: { name: 'Carga Demolidora', description: '+12% de ataque e +6% de vida.', effects: [{ effect: 'attack', value: 0.12 }, { effect: 'maxHp', value: 0.06 }] },
  metralhador: { name: 'Cadência Máxima', description: '+14% de velocidade de ataque e +8% de ataque.', effects: [{ effect: 'attackSpeed', value: 0.14 }, { effect: 'attack', value: 0.08 }] },
  artilheiro_flamejante: { name: 'Balas Incendiárias', description: '+10% de ataque e +5% de chance de crítico.', effects: [{ effect: 'attack', value: 0.1 }, { effect: 'crit', value: 0.05 }] },
};
