import type { Analyzer, GameState } from '../game/core/types';
import { gameStore } from '../game/core/GameStore';
import { itemById } from '../game/data/items';
import { MONSTERS } from '../game/data/monsters';
import { analyzerMetrics } from '../game/systems/analyzer';
import { compact, duration } from './format';

function Metric({label,value,detail,tone}:{label:string;value:string|number;detail?:string;tone?:string}){return <article className={`metric-card ${tone??''}`}><small>{label}</small><b>{value}</b>{detail&&<span>{detail}</span>}</article>}

function SessionSummary({analyzer,index}:{analyzer:Analyzer;index:number}){const metrics=analyzerMetrics(analyzer);return <article className="history-card"><div><b>Sessão {index+1}</b><small>{new Date(analyzer.startedAt).toLocaleString('pt-BR')}</small></div><span>{duration(metrics.activeSeconds)}</span><span>{compact(analyzer.xp)} XP</span><span>{compact(metrics.estimatedProfit)} lucro</span></article>}

export function AnalyzerPanel({state}:{state:GameState}){
  const analyzer=state.analyzer,metrics=analyzerMetrics(analyzer);const maxDamage=Math.max(1,...Object.values(analyzer.byCharacter));
  return <section><div className="section-heading"><div><span className="eyebrow">Sessão atual</span><h2>Hunt Analyzer</h2></div><button onClick={()=>gameStore.resetAnalyzer()}>Reiniciar estatísticas</button></div>
    <div className="analyzer-metrics"><Metric label="Tempo ativo" value={duration(metrics.activeSeconds)}/><Metric label="Experiência" value={compact(analyzer.xp)} detail={`${compact(metrics.xpPerHour)} / hora`} tone="xp-tone"/><Metric label="Ouro recebido" value={compact(analyzer.gold)} detail={`${compact(metrics.goldPerHour)} / hora`} tone="gold-tone"/><Metric label="Dano total" value={compact(analyzer.damage)} detail={`${compact(metrics.dps)} DPS`} tone="damage-tone"/><Metric label="Dano recebido" value={compact(analyzer.damageTaken)}/><Metric label="Cura realizada" value={compact(analyzer.healing)} tone="heal-tone"/><Metric label="Monstros" value={metrics.monsters} detail={`${analyzer.bosses} bosses`}/><Metric label="Ciclos" value={analyzer.cycles} detail={`${analyzer.defeats} derrotas`}/></div>
    <div className="analyzer-columns"><div className="analyzer-block"><h3>Distribuição de dano</h3>{state.characters.map(character=>{const damage=analyzer.byCharacter[character.id]??0;return <div className="damage-row" key={character.id}><span>{character.name}</span><div><i style={{width:`${damage/maxDamage*100}%`}}/></div><b>{compact(damage)}</b></div>})}</div><div className="analyzer-block profit-block"><h3>Lucro estimado</h3><dl><div><dt>Ouro efetivamente recebido</dt><dd>+ {compact(analyzer.gold)}</dd></div><div><dt>Venda estimada do loot</dt><dd>+ {compact(analyzer.lootValue)}</dd></div><div><dt>Custo dos consumíveis</dt><dd className="negative">− {compact(analyzer.suppliesValue)}</dd></div><div className="profit-total"><dt>Total estimado</dt><dd className={metrics.estimatedProfit>=0?'positive':'negative'}>{compact(metrics.estimatedProfit)} ouro</dd></div></dl><small>O valor de loot é uma estimativa de venda e não foi adicionado ao ouro recebido.</small></div></div>
    <div className="analyzer-columns"><div className="analyzer-block"><h3>Monstros derrotados</h3><div className="kill-list">{Object.entries(analyzer.kills).map(([id,count])=><span key={id}><b>{count}×</b>{MONSTERS[id]?.name??id}</span>)}{!Object.keys(analyzer.kills).length&&<p className="empty-state">Nenhum monstro derrotado nesta sessão.</p>}</div></div><div className="analyzer-block"><h3>Loot coletado</h3><div className="loot-list">{Object.entries(analyzer.loot).map(([id,count])=>{const item=itemById(id);return <span key={id}><b>{count}×</b>{item?.name??id}<small>{(item?.value??0)*count} ouro est.</small></span>})}{!Object.keys(analyzer.loot).length&&<p className="empty-state">Nenhum item coletado.</p>}</div><h4>Supplies consumidos · {metrics.supplies}</h4><div className="loot-list supplies">{Object.entries(analyzer.suppliesUsed).map(([id,count])=><span key={id}><b>{count}×</b>{itemById(id)?.name??id}</span>)}</div></div></div>
    <div className="history-section"><div className="subsection-heading"><h3>Histórico de sessões</h3><small>As últimas 20 sessões reiniciadas</small></div>{state.history.length?<div className="history-list">{state.history.slice().reverse().map((entry,index)=><SessionSummary key={`${entry.startedAt}-${index}`} analyzer={entry} index={state.history.length-index-1}/>)}</div>:<p className="empty-state">Use “Reiniciar estatísticas” para arquivar a sessão atual sem alterar personagens ou inventário.</p>}</div>
  </section>;
}
