import { useState } from 'react';
import type { GameState, InventoryStack, Stats } from '../game/core/types';
import { gameStore } from '../game/core/GameStore';
import { CLASSES } from '../game/data/classes';
import { itemById } from '../game/data/items';
import { itemDescription, itemIcon, slotNames, statNames } from './format';

type ContainerId='bp'|'loot'|'supply';type Selection={container:ContainerId;itemId:string};
const containerNames:Record<ContainerId,string>={bp:'Backpack',loot:'Loot Pouch',supply:'Supply Pouch'};

function ItemGrid({container,stacks,capacity,selected,onSelect}:{container:ContainerId;stacks:InventoryStack[];capacity:number;selected?:Selection;onSelect:(selection:Selection)=>void}){
  const used=stacks.reduce((sum,stack)=>sum+stack.quantity,0);
  return <section className="bag"><div className="bag-heading"><div><span className="bag-icon">▦</span><h3>{containerNames[container]}</h3></div><span className={used>=capacity?'capacity full':'capacity'}>{used}/{capacity}</span></div><div className="item-grid">{stacks.map(stack=>{const item=itemById(stack.itemId)!;return <button title={`${item.name} · ${item.rarity}`} className={`item-slot rarity-${item.rarity} ${selected?.container===container&&selected.itemId===item.id?'selected':''}`} key={item.id} onClick={()=>onSelect({container,itemId:item.id})}><span className="item-icon">{itemIcon(item)}</span><small>{item.name}</small><b>×{stack.quantity}</b></button>})}{!stacks.length&&<div className="empty-bag">Vazio</div>}</div></section>;
}

export function InventoryPanel({state,selectedCharacter}:{state:GameState;selectedCharacter:string}){
  const [selection,setSelection]=useState<Selection|undefined>(()=>{for(const container of ['bp','loot','supply'] as ContainerId[]){const itemId=state.inventory[container][0]?.itemId;if(itemId)return {container,itemId};}return undefined;});
  const character=state.characters.find(entry=>entry.id===selectedCharacter)??state.characters[0];const item=selection?itemById(selection.itemId):undefined;const stack=selection?state.inventory[selection.container].find(entry=>entry.itemId===selection.itemId):undefined;const equipped=item?.slot?itemById(character.equipment[item.slot]??''):undefined;const canEquip=!!item&&item.kind==='equipment'&&(!item.classIds||item.classIds.includes(character.classId))&&(item.level??1)<=character.profile.level;
  const comparedStats=item?.stats?Array.from(new Set([...Object.keys(item.stats),...Object.keys(equipped?.stats??{})])) as (keyof Stats)[]:[];
  return <section><div className="section-heading"><div><span className="eyebrow">Armazenamento</span><h2>Inventário</h2></div><div className="gold-display">◉ {state.gold.toLocaleString('pt-BR')} ouro</div></div><div className="inventory-layout"><div className="bags-column"><ItemGrid container="bp" stacks={state.inventory.bp} capacity={state.inventory.capacity.bp} selected={selection} onSelect={setSelection}/><ItemGrid container="loot" stacks={state.inventory.loot} capacity={state.inventory.capacity.loot} selected={selection} onSelect={setSelection}/><ItemGrid container="supply" stacks={state.inventory.supply} capacity={state.inventory.capacity.supply} selected={selection} onSelect={setSelection}/></div><aside className="item-detail stone-inset">{item&&selection?<><div className={`item-detail-icon rarity-${item.rarity}`}>{itemIcon(item)}</div><span className={`rarity-label rarity-${item.rarity}`}>{item.rarity}</span><h3>{item.name}</h3><p>{itemDescription(item)}</p><dl><div><dt>Quantidade</dt><dd>{stack?.quantity??0}</dd></div><div><dt>Valor unitário</dt><dd>{item.value} ouro</dd></div><div><dt>Nível necessário</dt><dd>{item.level??1}</dd></div><div><dt>Classes</dt><dd>{item.classIds?.map(id=>CLASSES[id].name).join(', ')??'Todas'}</dd></div>{item.slot&&<div><dt>Slot</dt><dd>{slotNames[item.slot]}</dd></div>}</dl>{item.stats&&<div className="item-stats"><h4>Atributos</h4>{Object.entries(item.stats).map(([key,value])=><span key={key}><small>{statNames[key as keyof Stats]}</small><b>+{typeof value==='number'&&value<1?`${Math.round(value*100)}%`:value}</b></span>)}</div>}{item.kind==='equipment'&&<div className="comparison"><h4>Comparação com {equipped?.name??'slot vazio'}</h4>{comparedStats.map(key=>{const next=item.stats?.[key]??0,current=equipped?.stats?.[key]??0,delta=next-current;return <div key={key}><span>{statNames[key]}</span><span>{current<1&&current>0?`${Math.round(current*100)}%`:current} → {next<1&&next>0?`${Math.round(next*100)}%`:next}</span><b className={delta>=0?'positive':'negative'}>{delta>=0?'+':''}{Math.abs(delta)<1&&delta!==0?`${Math.round(delta*100)}%`:delta}</b></div>})}</div>}<div className="item-actions">{canEquip&&stack&&<button className="primary" onClick={()=>gameStore.equip(character.id,item.id)}>Equipar em {character.name}</button>}{item.kind==='supply'&&stack&&<button className="primary" onClick={()=>gameStore.useSupply(character.id,item.id)}>Usar em {character.name}</button>}{stack&&<button className="danger" onClick={()=>gameStore.sell(selection.container,item.id)}>Vender 1</button>}</div></>:<div className="empty-detail">Selecione um item da mochila para ver detalhes e ações.</div>}</aside></div></section>;
}
