import type { GameState } from '../game/core/types';
import { gameStore } from '../game/core/GameStore';
import { SPELLS, spellById } from '../game/data/spells';
import { SPELL_SLOTS } from '../game/core/GameEngine';
import { PROFICIENCIES } from '../game/rpg/proficiencies';

export function SpellsPanel({state,selected}:{state:GameState;selected:string}){
  const character=state.characters.find(entry=>entry.id===selected)??state.characters[0];
  const available=SPELLS.filter(spell=>(spell.classId===character.classId||spell.universal)&&spell.level<=character.profile.level&&!character.spellSlots.includes(spell.id));
  const options=(<>{available.map(spell=>(<option key={spell.id} value={spell.id}>{spell.name}{spell.element?` · ${PROFICIENCIES[spell.element].name}`:''}</option>))}</>);
  return <section><div className="section-heading"><div><span className="eyebrow">Automação</span><h2>Rotação de {character.name}</h2></div><span className="section-note">A primeira magia liberada e válida é executada. Máx. {SPELL_SLOTS} magias; magias elementais treinam o elemento em foco.</span></div><div className="spell-list">{character.spellSlots.map((id,index)=>{const spell=spellById(id)!;const condition=character.spellConditions[id]??{};return <article className={`spell-card ${spell.level>character.profile.level?'locked':''}`} key={id}><div className="spell-order">{index+1}</div><div className="spell-copy"><b>{spell.name}</b><small>{spell.description} · Nv. {spell.level} · {spell.mana} mana · {spell.cooldown}s</small></div><div className="spell-actions"><select aria-label={`Trocar ${spell.name}`} value="" disabled={!available.length} onChange={event=>event.target.value&&gameStore.equipSpell(character.id,index,event.target.value)}><option value="">Trocar…</option>{options}</select><button title="Remover magia" onClick={()=>gameStore.unequipSpell(character.id,index)}>✕</button><button disabled={!index} onClick={()=>gameStore.reorderSpell(character.id,index,index-1)}>↑</button><button disabled={index===character.spellSlots.length-1} onClick={()=>gameStore.reorderSpell(character.id,index,index+1)}>↓</button></div><label>HP abaixo %<input type="number" min="0" max="100" value={condition.hpBelow??''} onChange={event=>gameStore.setSpellCondition(character.id,id,{hpBelow:event.target.value===''?undefined:+event.target.value})}/></label><label>Inimigos mín.<input type="number" min="1" max="4" value={condition.minEnemies??''} onChange={event=>gameStore.setSpellCondition(character.id,id,{minEnemies:event.target.value===''?undefined:+event.target.value})}/></label><label>Mana acima %<input type="number" min="0" max="100" value={condition.manaAbove??''} onChange={event=>gameStore.setSpellCondition(character.id,id,{manaAbove:event.target.value===''?undefined:+event.target.value})}/></label><label className="inline-check"><input type="checkbox" checked={!!condition.allyInjured} onChange={event=>gameStore.setSpellCondition(character.id,id,{allyInjured:event.target.checked})}/> aliado ferido</label></article>})}</div>{character.spellSlots.length<SPELL_SLOTS&&<label className="spell-add">Equipar magia<select value="" disabled={!available.length} onChange={event=>event.target.value&&gameStore.equipSpell(character.id,character.spellSlots.length,event.target.value)}><option value="">Escolher…</option>{options}</select></label>}</section>;
}
