import { describe, expect, it, vi } from 'vitest';
import { GameEngine } from './GameEngine';
import { characterStats, classLabel, gainExperience, xpForLevel } from '../systems/progression';
import { monsterHit } from '../systems/combat';
import type { Character, GameState } from './types';
const monsterHitFor=(state:GameState,c:Character)=>monsterHit({uid:'t',defId:'skeleton',hp:100,maxHp:100,cooldown:0,alive:true},c,state);
import { partyState } from './testing';

describe('GameEngine — hunt automática',()=>{
  it('congela combate e cooldowns quando pausado',()=>{const e=new GameEngine(partyState());e.start();e.tick(100);const s=e.getSnapshot();const hp=s.monsters[0].hp;e.pause();for(let i=0;i<30;i++)e.tick(100);expect(e.getSnapshot().monsters[0].hp).toBe(hp);expect(e.getSnapshot().status).toBe('paused');e.resume();e.tick(1000);expect(e.getSnapshot().status).not.toBe('paused');});
  it('mantém a escada aguardando quando avanço automático está desligado',()=>{const e=new GameEngine(partyState());e.start();e.setAutoAdvance(false);const s=e.getSnapshot();s.monsters.forEach(m=>{m.hp=1;});for(const c of s.characters)c.profile.level=50;for(let i=0;i<100&&e.getSnapshot().status!=='transition';i++)e.tick(100);for(let i=0;i<20;i++)e.tick(100);expect(e.getSnapshot().status).toBe('transition');e.advance();expect(e.getSnapshot().wave).toBe(1);expect(e.getSnapshot().status).toBe('running');});
  it('completa muitos ciclos sem multiplicar monstros ou timers',()=>{vi.spyOn(Math,'random').mockReturnValue(.99);const state=partyState();state.characters.forEach(c=>c.profile.level=80);const e=new GameEngine(state);e.start();for(let i=0;i<30000&&e.getSnapshot().cycle<20;i++)e.tick(100);expect(e.getSnapshot().cycle).toBeGreaterThanOrEqual(20);expect(e.getSnapshot().monsters.length).toBeLessThanOrEqual(2);expect(e.getSnapshot().analyzer.cycles).toBe(e.getSnapshot().cycle);vi.restoreAllMocks();});
  it('equipar e desequipar altera atributos e conserva o item',()=>{const e=new GameEngine(partyState());const s=e.getSnapshot();const knight=s.characters.find(c=>c.classId==='squire')!;const before=characterStats(knight,s).attack;expect(knight.equipment.weapon).toBe('rusty_sword');expect(e.unequip(knight.id,'weapon')).toBe(true);expect(characterStats(knight,e.getSnapshot()).attack).toBeLessThan(before);expect(e.equip(knight.id,'rusty_sword')).toBe(true);expect(characterStats(knight,e.getSnapshot()).attack).toBe(before);expect(e.unequip(knight.id,'weapon')).toBe(true);expect(e.getSnapshot().inventory.bp.find(x=>x.itemId==='rusty_sword')?.quantity).toBe(1);});
  it('reinicia somente o Analyzer e arquiva a sessão atual',()=>{const e=new GameEngine(partyState());const state=e.getSnapshot();state.analyzer.xp=120;state.gold=77;state.characters[0].profile.xp=45;e.resetAnalyzer();expect(e.getSnapshot().analyzer.xp).toBe(0);expect(e.getSnapshot().history).toHaveLength(1);expect(e.getSnapshot().history[0].xp).toBe(120);expect(e.getSnapshot().gold).toBe(77);expect(e.getSnapshot().characters[0].profile.xp).toBe(45);});
  it('registra quantidade e custo de supplies consumidos',()=>{const e=new GameEngine(partyState());const character=e.getSnapshot().characters[0];expect(e.useSupply(character.id,'health_potion')).toBe(true);expect(e.getSnapshot().analyzer.suppliesUsed.health_potion).toBe(1);expect(e.getSnapshot().analyzer.suppliesValue).toBe(12);});
  it('redistribui talentos, devolve pontos e cobra ouro uma única vez',()=>{const state=partyState();const knight=state.characters.find(c=>c.classId==='squire')!;knight.talents={squire_talent_0:2,squire_talent_2:1};knight.talentPoints=1;state.gold=500;const e=new GameEngine(state);expect(e.respecTalents(knight.id)).toBe(true);expect(knight.talents).toEqual({});expect(knight.talentPoints).toBe(4);expect(state.gold).toBe(275);expect(e.respecTalents(knight.id)).toBe(false);expect(state.gold).toBe(275);});
  it('não redistribui talentos quando o ouro é insuficiente',()=>{const state=partyState();const monk=state.characters.find(c=>c.classId==='squire')!;monk.talents={squire_talent_0:1};state.gold=74;const e=new GameEngine(state);expect(e.respecTalents(monk.id)).toBe(false);expect(monk.talents.squire_talent_0).toBe(1);expect(state.gold).toBe(74);});
  it('não inicia a hunt sem personagens',()=>{const e=new GameEngine();e.start();expect(e.getSnapshot().status).toBe('idle');});
});

describe('GameEngine — criação do grupo',()=>{
  it('começa sem personagens e pede a criação de 3',()=>{const s=new GameEngine().getSnapshot();expect(s.characters).toHaveLength(0);expect(s.team).toHaveLength(0);expect(s.message).toMatch(/3 personagens/);});
  it('cria 3 Squires nível 1, nomeados e escalados para a equipe',()=>{const e=new GameEngine();expect(e.createParty(['  Aldric ','Kael','Lyra'])).toBe(true);const s=e.getSnapshot();expect(s.characters.map(c=>c.name)).toEqual(['Aldric','Kael','Lyra']);expect(s.team).toEqual(s.characters.map(c=>c.id));for(const c of s.characters){expect(c.classId).toBe('squire');expect(c.profile.classId).toBe('aprendiz');expect(c.profile.level).toBe(1);expect(c.profile.proficiencies.melee.level).toBe(10);expect(c.equipment.weapon).toBe('rusty_sword');}});
  it('rejeita nomes vazios, repetidos, quantidade errada e segunda criação',()=>{const e=new GameEngine();expect(e.createParty(['A','B'])).toBe(false);expect(e.createParty(['A','','C'])).toBe(false);expect(e.createParty(['A','a','C'])).toBe(false);expect(e.getSnapshot().characters).toHaveLength(0);expect(e.createParty(['A','B','C'])).toBe(true);expect(e.createParty(['D','E','F'])).toBe(false);expect(e.getSnapshot().characters).toHaveLength(3);});
  it('recruta Squires extras até o limite do grupo de reserva',()=>{const e=new GameEngine(partyState());expect(e.recruit('Nova')).toBe(true);expect(e.recruit('nova')).toBe(false);expect(e.recruit('Outra')).toBe(true);expect(e.recruit('Demais')).toBe(false);expect(e.getSnapshot().characters).toHaveLength(5);});
});

describe('GameEngine — camada RPG em combate',()=>{
  it('treina a proficiência da arma por tempo, credita XP no perfil e conta ouro e chefes',()=>{
    vi.spyOn(Math,'random').mockReturnValue(.99);const state=partyState();state.characters.forEach(c=>{c.profile.level=40;});const e=new GameEngine(state);e.start();
    for(let i=0;i<30000&&e.getSnapshot().cycle<1;i++)e.tick(100);
    const c=e.getSnapshot().characters[0];expect(c.profile.proficiencies.melee.level*1+c.profile.proficiencies.melee.tries).toBeGreaterThan(10);expect(c.profile.trainingFocus).toBeDefined();expect(c.profile.counters.goldEarned).toBeGreaterThan(0);expect(c.profile.counters.bossKills).toBe(1);vi.restoreAllMocks();
  });
  it('conta dano sofrido e treina Defesa quando o golpe é aparado',()=>{const state=partyState();const c=state.characters[0];monsterHitFor(state,c);expect(c.profile.counters.damageTaken).toBeGreaterThan(0);expect(c.profile.proficiencies.defense.tries+c.profile.proficiencies.defense.level).toBeGreaterThan(10);});
  it('cada nível ganho rende um ponto de talento',()=>{const e=new GameEngine(partyState());const c=e.getSnapshot().characters[0];gainExperience(c,xpForLevel(1)+xpForLevel(2)+5);expect(c.profile.level).toBe(3);expect(c.profile.xp).toBe(5);expect(c.talentPoints).toBe(2);});
  it('evolui a classe pelo motor só quando os requisitos são cumpridos',()=>{const e=new GameEngine(partyState());const c=e.getSnapshot().characters[0];expect(e.evolve(c.id,'guerreiro')).toBe(false);expect(c.profile.classId).toBe('aprendiz');c.profile.level=10;c.profile.proficiencies.melee.level=15;expect(e.evolve(c.id,'guerreiro')).toBe(true);expect(c.profile.classPath).toEqual(['aprendiz','guerreiro']);expect(classLabel(c)).toBe('Guerreiro');expect(e.evolve(c.id,'guardiao')).toBe(false);const stats=characterStats(c,e.getSnapshot());expect(stats.maxHp).toBeGreaterThan(0);});
  it('treino offline credita só tries ao alvo e gera relatório',()=>{const e=new GameEngine(partyState());const [a,b]=e.getSnapshot().characters;e.setOfflineTarget(a.id,'ranged');const xp=a.profile.xp;e.applyOffline(3600);const report=e.getSnapshot().offlineReport!;expect(report.entries).toHaveLength(1);expect(report.entries[0].target).toBe('ranged');expect(a.profile.xp).toBe(xp);expect(a.profile.proficiencies.ranged.tries+a.profile.proficiencies.ranged.level).toBeGreaterThan(10);expect(b.profile.lastTrained).toBeUndefined();e.dismissOfflineReport();expect(e.getSnapshot().offlineReport).toBeUndefined();});
});
