import { useMemo, useState, useSyncExternalStore } from 'react';
import { PhaserGame } from './PhaserGame';
import { gameStore } from './game/core/GameStore';
import { CLASSES } from './game/data/classes';
import { ITEMS, itemById } from './game/data/items';
import { spellById } from './game/data/spells';
import { characterStats, xpForLevel } from './game/systems/progression';
import type { Character, ClassId } from './game/core/types';

type Tab='Equipe'|'Personagens'|'Magias'|'Inventário';
const pct=(a:number,b:number)=>Math.round(a/Math.max(1,b)*100);

function TeamPanel({selected,setSelected}:{selected:string;setSelected:(id:string)=>void}){
  const s=useSyncExternalStore(gameStore.subscribe,gameStore.getSnapshot);return <aside className="team-panel"><h2>Equipe</h2>{s.team.map(id=>s.characters.find(c=>c.id===id)).filter(Boolean).map(c=>{const ch=c as Character,st=characterStats(ch,s);return <button key={ch.id} className={`hero-card ${selected===ch.id?'selected':''}`} onClick={()=>setSelected(ch.id)}><span><b>{ch.name}</b><small>{CLASSES[ch.classId].name} · Nv. {ch.level}</small></span><label>HP {Math.round(ch.hp)}/{st.maxHp}</label><i><em style={{width:`${pct(ch.hp,st.maxHp)}%`}}/></i><label>Mana {Math.round(ch.mana)}/{st.maxMana}</label><i className="mana"><em style={{width:`${pct(ch.mana,st.maxMana)}%`}}/></i><small>{ch.effects.length?ch.effects.map(e=>e.type).join(', '):'Sem efeitos'}</small></button>})}</aside>;
}
function Characters({selected,setSelected}:{selected:string;setSelected:(id:string)=>void}){const s=useSyncExternalStore(gameStore.subscribe,gameStore.getSnapshot);const c=s.characters.find(x=>x.id===selected)??s.characters[0];const st=characterStats(c,s);const [name,setName]=useState(c.name);const missing=(Object.keys(CLASSES) as ClassId[]).filter(id=>!s.characters.some(c=>c.classId===id));return <div className="panel-grid"><section><h3>Personagens</h3>{s.characters.map(ch=><div className="row" key={ch.id}><button className="link" onClick={()=>{setSelected(ch.id);setName(ch.name)}}>{ch.name} · {CLASSES[ch.classId].name}</button><label><input type="checkbox" checked={s.team.includes(ch.id)} onChange={()=>gameStore.toggleTeam(ch.id)}/> equipe</label></div>)}{missing.map(id=><button key={id} onClick={()=>gameStore.create(id,CLASSES[id].name)}>Criar {CLASSES[id].name}</button>)}</section><section><h3>{c.name}</h3><div className="row"><input value={name} onChange={e=>setName(e.target.value)} maxLength={18}/><button onClick={()=>gameStore.rename(c.id,name)}>Renomear</button></div><p>Nível {c.level} · XP {c.xp}/{xpForLevel(c.level)} · Pontos de talento {c.talentPoints}</p><div className="stats"><span>Ataque <b>{Math.round(st.attack)}</b></span><span>Defesa <b>{Math.round(st.defense)}</b></span><span>Velocidade <b>{st.attackSpeed.toFixed(2)}/s</b></span><span>Crítico <b>{pct(st.crit,1)}%</b></span><span>Resistência <b>{pct(st.resistance,1)}%</b></span><span>Magic Lv <b>{c.skills.magic.level}</b></span></div><h4>Habilidades</h4><div className="skills">{Object.entries(c.skills).map(([k,v])=><span key={k}>{k} <b>{v.level}</b></span>)}</div><h4>Equipamentos</h4>{(['helmet','armor','legs','boots','weapon','offhand','amulet','ring'] as const).map(slot=><div className="row" key={slot}><span>{slot}: {itemById(c.equipment[slot]??'')?.name??'vazio'}</span>{c.equipment[slot]&&<button onClick={()=>gameStore.unequip(c.id,slot)}>Remover</button>}</div>)}</section></div>}
function Spells({selected}:{selected:string}){const s=useSyncExternalStore(gameStore.subscribe,gameStore.getSnapshot);const c=s.characters.find(x=>x.id===selected)??s.characters[0];return <section><h3>Rotação de {c.name}</h3><p>A primeira magia liberada, com mana e condições válidas, é executada. Sem opção válida, o ataque básico assume.</p>{c.spellSlots.map((id,i)=>{const sp=spellById(id)!;const cond=c.spellConditions[id]??{};return <article className={`spell ${sp.level>c.level?'locked':''}`} key={id}><div><b>{i+1}. {sp.name}</b><small>{sp.description} · Nv. {sp.level} · {sp.mana} mana · {sp.cooldown}s</small></div><div className="spell-actions"><button disabled={!i} onClick={()=>gameStore.reorderSpell(c.id,i,i-1)}>↑</button><button disabled={i===c.spellSlots.length-1} onClick={()=>gameStore.reorderSpell(c.id,i,i+1)}>↓</button></div><label>HP abaixo % <input type="number" min="0" max="100" value={cond.hpBelow??''} onChange={e=>gameStore.setSpellCondition(c.id,id,{hpBelow:e.target.value===''?undefined:+e.target.value})}/></label><label>Inimigos mín. <input type="number" min="1" max="4" value={cond.minEnemies??''} onChange={e=>gameStore.setSpellCondition(c.id,id,{minEnemies:e.target.value===''?undefined:+e.target.value})}/></label><label>Mana acima % <input type="number" min="0" max="100" value={cond.manaAbove??''} onChange={e=>gameStore.setSpellCondition(c.id,id,{manaAbove:e.target.value===''?undefined:+e.target.value})}/></label><label><input type="checkbox" checked={!!cond.allyInjured} onChange={e=>gameStore.setSpellCondition(c.id,id,{allyInjured:e.target.checked})}/> aliado ferido</label></article>})}</section>}
function Inventory({selected}:{selected:string}){const s=useSyncExternalStore(gameStore.subscribe,gameStore.getSnapshot);const selectedChar=s.characters.find(c=>c.id===selected)??s.characters[0];return <section><h3>Inventário · {s.gold} ouro</h3>{(['bp','loot','supply'] as const).map(box=>{const label={bp:'BP',loot:'Loot Pouch',supply:'Supply Pouch'}[box];const used=s.inventory[box].reduce((n,x)=>n+x.quantity,0);return <div className="inventory" key={box}><h4>{label} <small>{used}/{s.inventory.capacity[box]}</small></h4>{!s.inventory[box].length&&<p className="muted">Vazio</p>}{s.inventory[box].map(stack=>{const item=itemById(stack.itemId)!;const canEquip=item.kind==='equipment'&&(!item.classIds||item.classIds.includes(selectedChar.classId))&&(item.level??1)<=selectedChar.level;return <div className={`item ${item.rarity}`} key={stack.itemId}><span><b>{item.name}</b> ×{stack.quantity}<small>{item.rarity} · valor {item.value}{item.level?` · Nv. ${item.level}`:''}</small></span>{canEquip&&<button onClick={()=>gameStore.equip(selectedChar.id,item.id)}>Equipar</button>}{item.kind==='supply'&&<button onClick={()=>gameStore.useSupply(selectedChar.id,item.id)}>Usar</button>}<button onClick={()=>gameStore.sell(box,item.id)}>Vender</button></div>})}</div>})}<details><summary>Catálogo ({ITEMS.length} itens)</summary>{ITEMS.map(i=><small className={i.rarity} key={i.id}>{i.name} · </small>)}</details></section>}
function App(){const s=useSyncExternalStore(gameStore.subscribe,gameStore.getSnapshot);const [tab,setTab]=useState<Tab>('Equipe');const [selected,setSelected]=useState(s.team[0]??s.characters[0].id);const active=useMemo(()=>Math.max(1,s.analyzer.activeMs/1000),[s.analyzer.activeMs]);return <div id="app"><header><div><h1>Tiny Dungeon</h1><span>{s.status.toUpperCase()} · Wave {s.wave+1}/3 · Ciclo {s.cycle+1}</span></div><div className="controls"><button disabled={s.status!=='idle'} onClick={()=>gameStore.start()}>Iniciar</button><button disabled={s.status==='idle'||s.status==='paused'} onClick={()=>gameStore.pause()}>Pausar</button><button disabled={s.status!=='paused'} onClick={()=>gameStore.resume()}>Continuar</button><button disabled={s.status==='idle'} className="danger" onClick={()=>gameStore.end()}>Encerrar Hunt</button><label className="toggle"><input type="checkbox" checked={s.autoAdvance} onChange={e=>gameStore.setAutoAdvance(e.target.checked)}/> avanço automático</label>{s.status==='transition'&&!s.autoAdvance&&<button onClick={()=>gameStore.advance()}>Descer agora</button>}</div></header><main><div className="game-column"><PhaserGame/><nav>{(['Equipe','Personagens','Magias','Inventário'] as Tab[]).map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</nav><div className="tab-content">{tab==='Equipe'&&<section><h3>Resumo da expedição</h3><div className="stats"><span>XP <b>{s.analyzer.xp}</b></span><span>Ouro <b>{s.analyzer.gold}</b></span><span>Dano <b>{s.analyzer.damage}</b></span><span>DPS <b>{(s.analyzer.damage/active).toFixed(1)}</b></span><span>Abates <b>{Object.values(s.analyzer.kills).reduce((a,b)=>a+b,0)}</b></span><span>Derrotas <b>{s.analyzer.defeats}</b></span></div><p>{s.message}</p></section>}{tab==='Personagens'&&<Characters selected={selected} setSelected={setSelected}/>} {tab==='Magias'&&<Spells selected={selected}/>} {tab==='Inventário'&&<Inventory selected={selected}/>}</div></div><TeamPanel selected={selected} setSelected={setSelected}/></main></div>}
export default App;
