import { useMemo, useRef, useState, useSyncExternalStore, type ChangeEvent } from 'react';
import { PhaserGame } from './PhaserGame';
import { gameStore, importGameBackup, saveNow } from './game/core/GameStore';
import { exportBackup } from './game/persistence/backup';
import { CLASSES } from './game/data/classes';
import { ITEMS, itemById } from './game/data/items';
import { spellById } from './game/data/spells';
import { characterStats, xpForLevel } from './game/systems/progression';
import type { Character, ClassId } from './game/core/types';

type Tab='Equipe'|'Personagens'|'Magias'|'Inventário';
const pct=(a:number,b:number)=>Math.round(a/Math.max(1,b)*100);

function TeamPanel({selected,setSelected}:{selected:string;setSelected:(id:string)=>void}){
  const state=useSyncExternalStore(gameStore.subscribe,gameStore.getSnapshot);
  const team=state.team.map(id=>state.characters.find(c=>c.id===id)).filter(Boolean) as Character[];
  return <aside className="team-panel"><h2>Equipe</h2>{team.map(character=>{const stats=characterStats(character,state);return <button key={character.id} className={`hero-card ${selected===character.id?'selected':''}`} onClick={()=>setSelected(character.id)}><span><b>{character.name}</b><small>{CLASSES[character.classId].name} · Nv. {character.level}</small></span><label>HP {Math.round(character.hp)}/{stats.maxHp}</label><i><em style={{width:`${pct(character.hp,stats.maxHp)}%`}}/></i><label>Mana {Math.round(character.mana)}/{stats.maxMana}</label><i className="mana"><em style={{width:`${pct(character.mana,stats.maxMana)}%`}}/></i><small>{character.effects.length?character.effects.map(e=>e.type).join(', '):'Sem efeitos'}</small></button>})}</aside>;
}

function Characters({selected,setSelected}:{selected:string;setSelected:(id:string)=>void}){
  const state=useSyncExternalStore(gameStore.subscribe,gameStore.getSnapshot);const character=state.characters.find(x=>x.id===selected)??state.characters[0];const stats=characterStats(character,state);const [name,setName]=useState(character.name);const missing=(Object.keys(CLASSES) as ClassId[]).filter(id=>!state.characters.some(c=>c.classId===id));
  return <div className="panel-grid"><section><h3>Personagens</h3>{state.characters.map(ch=><div className="row" key={ch.id}><button className="link" onClick={()=>{setSelected(ch.id);setName(ch.name)}}>{ch.name} · {CLASSES[ch.classId].name}</button><label><input type="checkbox" checked={state.team.includes(ch.id)} onChange={()=>gameStore.toggleTeam(ch.id)}/> equipe</label></div>)}{missing.map(id=><button key={id} onClick={()=>gameStore.create(id,CLASSES[id].name)}>Criar {CLASSES[id].name}</button>)}</section><section><h3>{character.name}</h3><div className="row"><input value={name} onChange={e=>setName(e.target.value)} maxLength={18}/><button onClick={()=>gameStore.rename(character.id,name)}>Renomear</button></div><p>Nível {character.level} · XP {character.xp}/{xpForLevel(character.level)} · Pontos de talento {character.talentPoints}</p><div className="stats"><span>Ataque <b>{Math.round(stats.attack)}</b></span><span>Defesa <b>{Math.round(stats.defense)}</b></span><span>Velocidade <b>{stats.attackSpeed.toFixed(2)}/s</b></span><span>Crítico <b>{pct(stats.crit,1)}%</b></span><span>Resistência <b>{pct(stats.resistance,1)}%</b></span><span>Magic Lv <b>{character.skills.magic.level}</b></span></div><h4>Habilidades</h4><div className="skills">{Object.entries(character.skills).map(([key,value])=><span key={key}>{key} <b>{value.level}</b></span>)}</div><h4>Equipamentos</h4>{(['helmet','armor','legs','boots','weapon','offhand','amulet','ring'] as const).map(slot=><div className="row" key={slot}><span>{slot}: {itemById(character.equipment[slot]??'')?.name??'vazio'}</span>{character.equipment[slot]&&<button onClick={()=>gameStore.unequip(character.id,slot)}>Remover</button>}</div>)}</section></div>;
}

function Spells({selected}:{selected:string}){
  const state=useSyncExternalStore(gameStore.subscribe,gameStore.getSnapshot);const character=state.characters.find(x=>x.id===selected)??state.characters[0];
  return <section><h3>Rotação de {character.name}</h3><p>A primeira magia liberada, com mana e condições válidas, é executada. Sem opção válida, o ataque básico assume.</p>{character.spellSlots.map((id,index)=>{const spell=spellById(id)!;const condition=character.spellConditions[id]??{};return <article className={`spell ${spell.level>character.level?'locked':''}`} key={id}><div><b>{index+1}. {spell.name}</b><small>{spell.description} · Nv. {spell.level} · {spell.mana} mana · {spell.cooldown}s</small></div><div className="spell-actions"><button disabled={!index} onClick={()=>gameStore.reorderSpell(character.id,index,index-1)}>↑</button><button disabled={index===character.spellSlots.length-1} onClick={()=>gameStore.reorderSpell(character.id,index,index+1)}>↓</button></div><label>HP abaixo % <input type="number" min="0" max="100" value={condition.hpBelow??''} onChange={e=>gameStore.setSpellCondition(character.id,id,{hpBelow:e.target.value===''?undefined:+e.target.value})}/></label><label>Inimigos mín. <input type="number" min="1" max="4" value={condition.minEnemies??''} onChange={e=>gameStore.setSpellCondition(character.id,id,{minEnemies:e.target.value===''?undefined:+e.target.value})}/></label><label>Mana acima % <input type="number" min="0" max="100" value={condition.manaAbove??''} onChange={e=>gameStore.setSpellCondition(character.id,id,{manaAbove:e.target.value===''?undefined:+e.target.value})}/></label><label><input type="checkbox" checked={!!condition.allyInjured} onChange={e=>gameStore.setSpellCondition(character.id,id,{allyInjured:e.target.checked})}/> aliado ferido</label></article>})}</section>;
}

function Inventory({selected}:{selected:string}){
  const state=useSyncExternalStore(gameStore.subscribe,gameStore.getSnapshot);const character=state.characters.find(c=>c.id===selected)??state.characters[0];
  return <section><h3>Inventário · {state.gold} ouro</h3>{(['bp','loot','supply'] as const).map(box=>{const label={bp:'BP',loot:'Loot Pouch',supply:'Supply Pouch'}[box];const used=state.inventory[box].reduce((n,x)=>n+x.quantity,0);return <div className="inventory" key={box}><h4>{label} <small>{used}/{state.inventory.capacity[box]}</small></h4>{!state.inventory[box].length&&<p className="muted">Vazio</p>}{state.inventory[box].map(stack=>{const item=itemById(stack.itemId)!;const canEquip=item.kind==='equipment'&&(!item.classIds||item.classIds.includes(character.classId))&&(item.level??1)<=character.level;return <div className={`item ${item.rarity}`} key={stack.itemId}><span><b>{item.name}</b> ×{stack.quantity}<small>{item.rarity} · valor {item.value}{item.level?` · Nv. ${item.level}`:''}</small></span>{canEquip&&<button onClick={()=>gameStore.equip(character.id,item.id)}>Equipar</button>}{item.kind==='supply'&&<button onClick={()=>gameStore.useSupply(character.id,item.id)}>Usar</button>}<button onClick={()=>gameStore.sell(box,item.id)}>Vender</button></div>})}</div>})}<details><summary>Catálogo ({ITEMS.length} itens)</summary>{ITEMS.map(item=><small className={item.rarity} key={item.id}>{item.name} · </small>)}</details></section>;
}

function App(){
  const state=useSyncExternalStore(gameStore.subscribe,gameStore.getSnapshot);const [tab,setTab]=useState<Tab>('Equipe');const [selected,setSelected]=useState(state.team[0]??state.characters[0].id);const [backupMessage,setBackupMessage]=useState('');const fileInput=useRef<HTMLInputElement>(null);const active=useMemo(()=>Math.max(1,state.analyzer.activeMs/1000),[state.analyzer.activeMs]);
  const downloadBackup=async()=>{await saveNow();const blob=new Blob([exportBackup(gameStore.getSnapshot())],{type:'application/json'});const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=`tiny-dungeon-${new Date().toISOString().slice(0,10)}.json`;document.body.append(anchor);anchor.click();anchor.remove();window.setTimeout(()=>URL.revokeObjectURL(url),1000);setBackupMessage('Backup exportado.');};
  const uploadBackup=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];event.target.value='';if(!file)return;try{const restored=await importGameBackup(await file.text());setSelected(restored.team[0]??restored.characters[0].id);setBackupMessage('Backup validado e restaurado.');}catch(error){setBackupMessage(error instanceof Error?error.message:'Não foi possível importar o backup.');}};
  return <div id="app"><header><div><h1>Tiny Dungeon</h1><span>{state.status.toUpperCase()} · Wave {state.wave+1}/3 · Ciclo {state.cycle+1}</span></div><div className="controls"><button disabled={state.status!=='idle'} onClick={()=>gameStore.start()}>Iniciar</button><button disabled={state.status==='idle'||state.status==='paused'} onClick={()=>gameStore.pause()}>Pausar</button><button disabled={state.status!=='paused'} onClick={()=>gameStore.resume()}>Continuar</button><button disabled={state.status==='idle'} className="danger" onClick={()=>gameStore.end()}>Encerrar Hunt</button><label className="toggle"><input type="checkbox" checked={state.autoAdvance} onChange={e=>gameStore.setAutoAdvance(e.target.checked)}/> avanço automático</label>{state.status==='transition'&&!state.autoAdvance&&<button onClick={()=>gameStore.advance()}>Descer agora</button>}<button onClick={()=>void downloadBackup()}>Exportar JSON</button><button onClick={()=>fileInput.current?.click()}>Importar backup</button><input ref={fileInput} hidden type="file" accept="application/json,.json" onChange={event=>void uploadBackup(event)}/>{backupMessage&&<output>{backupMessage}</output>}</div></header><main><div className="game-column"><PhaserGame/><nav>{(['Equipe','Personagens','Magias','Inventário'] as Tab[]).map(name=><button key={name} className={tab===name?'active':''} onClick={()=>setTab(name)}>{name}</button>)}</nav><div className="tab-content">{tab==='Equipe'&&<section><h3>Resumo da expedição</h3><div className="stats"><span>XP <b>{state.analyzer.xp}</b></span><span>Ouro <b>{state.analyzer.gold}</b></span><span>Dano <b>{state.analyzer.damage}</b></span><span>DPS <b>{(state.analyzer.damage/active).toFixed(1)}</b></span><span>Abates <b>{Object.values(state.analyzer.kills).reduce((a,b)=>a+b,0)}</b></span><span>Derrotas <b>{state.analyzer.defeats}</b></span></div><p>{state.message}</p></section>}{tab==='Personagens'&&<Characters selected={selected} setSelected={setSelected}/>} {tab==='Magias'&&<Spells selected={selected}/>} {tab==='Inventário'&&<Inventory selected={selected}/>}</div></div><TeamPanel selected={selected} setSelected={setSelected}/></main></div>;
}
export default App;
